spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mytheresa
    username: root
    password: root
    driverClassName: mysqlDriver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        use-sql-comments: true
        format_sql: true

logging:
  level.org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
