server:
  port: 8080
  servlet:
    context-path: /

# This was used for debug but this configuration needs to be an argument when project is called
#spring:
#  profiles:
#    active: local

# Max records returned by database to send in response
response:
  max-records: 5